if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }/*FB_PKG_DELIM*/

__d("useCometLogout",["CometPlaceholder.react","deferredLoadComponent","react","recoverableViolation","requireDeferred"],function(a,b,c,d,e,f,g){"use strict";var h=d("react");e=d("react");var i=e.useCallback,j=e.useContext,k=e.useRef,l=e.useState,m=c("deferredLoadComponent")(c("requireDeferred")("LogoutHandler.react").__setRef("useCometLogout")),n=h.createContext(function(){c("recoverableViolation")("No provider of CometLogoutContext exists","comet_infra")});function a(a){a=a.children;var b=l(!1),d=b[0],e=b[1],f=k();b=i(function(){f.current!=null?f.current.logout():e(!0)},[]);return h.jsxs(n.Provider,{value:b,children:[h.jsx(c("CometPlaceholder.react"),{fallback:null,children:h.jsx(m,{ref:f,shouldInitiateLogout:d})}),a]})}a.displayName=a.name+" [from "+f.id+"]";function b(){return j(n)}g.CometLogoutProvider=a;g.useCometLogout=b},98);
__d("maybeCoerceRouteParams",[],function(a,b,c,d,e,f){"use strict";function a(a,b){if(a==null)return null;switch(b){case"BOOL":if(typeof a==="boolean")return a;b=String(a).toLowerCase();return b==="0"||b==="false"?!1:Boolean(a);case"STRING":return String(a)}return a}f["default"]=a},66);
__d("MWCMGating.re",["MWCMGating.bs"],function(a,b,c,d,e,f){a=b("MWCMGating.bs").isJewelEnabled;f.isJewelEnabled=a},null);
__d("MAWInitSyncComplete.bs",[],function(a,b,c,d,e,f){"use strict";a=[0,1e3];f.id=a},null);
__d("MWLSDatabaseNames.bs",["CurrentUserInitialData"],function(a,b,c,d,e,f){"use strict";var g;a="GlobalStore"+(g||b("CurrentUserInitialData")).USER_ID;c="LightSpeed";f.globalStore=a;f.lightspeedPrefix=c},null);
__d("MWLSIndexedDBName.bs",["CurrentUserInitialData","MWLSDatabaseNames.bs"],function(a,b,c,d,e,f){"use strict";var g;function a(a){return b("MWLSDatabaseNames.bs").lightspeedPrefix+(g||(g=b("CurrentUserInitialData"))).USER_ID}f.dbName=a},null);
__d("MWLSIndexedDBName.re",["MWLSIndexedDBName.bs"],function(a,b,c,d,e,f){a=b("MWLSIndexedDBName.bs").dbName;f.dbName=a},null);
__d("MWIndexedDBDelete",["MWLSIndexedDBName.re","ODS","recoverableViolation"],function(a,b,c,d,e,f,g){"use strict";function a(){var a;if(((a=window)==null?void 0:a.indexedDB)!=null)if(typeof window.indexedDB.databases==="function"){a=window.indexedDB.databases();a.then(function(a){a.forEach(function(a){a=a.name||"";if(a.includes("LightSpeed")){a=window.indexedDB.deleteDatabase(a);a.onsuccess=function(){d("ODS").bumpEntityKey(3185,"mw_pdb_delete","success")};a.onblocked=function(){c("recoverableViolation")("[db clean up patch] Cannot delete db: blocked","messenger_web_product"),d("ODS").bumpEntityKey(3185,"mw_pdb_delete","blocked")};a.onerror=function(){d("ODS").bumpEntityKey(3185,"mw_pdb_delete","error"),c("recoverableViolation")("[pdb clean up patch] Cannot delete db","messenger_web_product")}}})})["catch"](function(){c("recoverableViolation")("[pdb clean up patch] LS delete databases error","messenger_web_product")})}else{a=window.indexedDB.deleteDatabase(d("MWLSIndexedDBName.re").dbName());a.onsuccess=function(){d("ODS").bumpEntityKey(3185,"mw_pdb_delete","success_v2")};a.onblocked=function(){c("recoverableViolation")("[db clean up patch v2] Cannot delete db: blocked","messenger_web_product"),d("ODS").bumpEntityKey(3185,"mw_pdb_delete","blocked_v2")};a.onerror=function(){d("ODS").bumpEntityKey(3185,"mw_pdb_delete","error_v2"),c("recoverableViolation")("[pdb clean up patch v2] Cannot delete db","messenger_web_product")}}}g.deleteAllDBs=a},98);
__d("ReStoreProvider.react",["react"],function(a,b,c,d,e,f,g){"use strict";var h=d("react"),i=h.createContext();function a(a){var b=a.children;a=a.db;return h.jsx(i.Provider,{value:a,children:b})}a.displayName=a.name+" [from "+f.id+"]";g.context=i;g.ReStoreProvider=a},98);
__d("EmptyStream",["Promise"],function(a,b,c,d,e,f){"use strict";a={amendWithoutAck:function(a){},amendWithAck:function(a){return new(b("Promise"))(function(){return!1})},cancel:function(){},start:function(){return new(b("Promise"))(function(){return null})}};c=a;f["default"]=c},66);
__d("ThrottlingClient",["EmptyStream","Promise","RtiWebRequestStreamClient","TransportSelectingClientUtils","gkx"],function(a,b,c,d,e,f,g){a=function(){function a(a){this.$2=c("RtiWebRequestStreamClient").ThrottledMethods,this.$1=a}var e=a.prototype;e.createStream=function(a,e,f,g,h){var i=d("TransportSelectingClientUtils").getMethodContextForCC(a.method,a.topic);if(c("gkx")("1682")&&this.$2[i]){g.onTermination("RequestStream method "+i+" has been throttled on this client");return b("Promise").resolve(c("EmptyStream"))}return this.$1.createStream(a,e,f,g,h)};return a}();g["default"]=a},98);
__d("WorkplaceWebMessagingQuickLogModule",[],function(a,b,c,d,e,f){a=Object.freeze({CHAT_MESSAGE_LIST_LOAD_TIME:1036591326,CHAT_MORE_MESSAGE_LIST_LOAD_TIME:1036596010,CHAT_MORE_THREADS_LOAD_TIME:1036594911,CHAT_PINNED_THREADS_LOAD_TIME:1036586287,CHAT_THREADS_LOAD_TIME:1036588047,CREATE_CHAT_THREAD:1036594803,CUSTOMER_SATISFACTION_SURVEY:1036597559,GROUP_ADD_MEMBER:1036595192,GROUP_REMOVE_MEMBER:1036592539,MESSAGE_SEND:1036587559});f["default"]=a},66);
__d("XCometMessengerControllerRouteBuilder",["jsExtraRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsExtraRouteBuilder")("/messages/t/{?thread_key}/{?*extra_junk}/",Object.freeze({}),["/messages/archived/new/","/messages/filtered/","/messages/filtered/new/","/messages/filtered/t/{?thread_key}/","/messages/gallery/","/messages/groups/","/messages/groups/new/","/messages/groups/t/{?thread_key}/","/messages/people/","/messages/people/new/","/messages/people/t/{?thread_key}/","/messages/requests/new/","/messages/new/","/messages/read/","/messages/search/","/messages/search/t/{?thread_key}/","/messages/search/new/"],void 0);b=a;g["default"]=b}),98);
__d("ReactDOM.classic.profiling",["cr:1344488"],(function(a,b,c,d,e,f){e.exports=b("cr:1344488")}),null);
__d("react-relay/relay-hooks/useClientQuery",["react-relay/relay-hooks/useLazyLoadQuery"],function(a,b,c,d,e,f){"use strict";function a(a,c,d){a=a;return b("react-relay/relay-hooks/useLazyLoadQuery")(a,c,babelHelpers["extends"]({},d,{fetchPolicy:"store-only"}))}e.exports=a},null);